// Base compartilhada opcional. Uma transação protege a revisão global contra sobrescrita concorrente.
import {initializeApp,getApps} from 'https://www.gstatic.com/firebasejs/10.13.0/firebase-app.js';
import {getAuth,signInWithEmailAndPassword} from 'https://www.gstatic.com/firebasejs/10.13.0/firebase-auth.js';
import {getFirestore,doc,collection,getDocs,query,where,runTransaction} from 'https://www.gstatic.com/firebasejs/10.13.0/firebase-firestore.js';
const config={apiKey:'AIzaSyAg3RZPbYEYz-FU9-kGICmXmHV58UImeFQ',authDomain:'central-spx-fiedler.firebaseapp.com',projectId:'central-spx-fiedler',storageBucket:'central-spx-fiedler.firebasestorage.app',messagingSenderId:'1009454162688',appId:'1:1009454162688:web:b81a72c90d13572fb409e5'};
const names={'alison@fiedler.com.br':'Alison Körtelt','caua@fiedler.com.br':'Cauã Pitz','murilo@fiedler.com.br':'Murilo Lini'};
export async function connect(email,password){const app=getApps().find(x=>x.name==='pro')||initializeApp(config,'pro'),auth=getAuth(app);const credential=await signInWithEmailAndPassword(auth,email,password);if(!names[credential.user.email])throw Error('Conta não autorizada para este piloto.');const db=getFirestore(app),meta=doc(db,'proWorkspace','main');let revision=0,baseline={};
return {name:names[credential.user.email],async load(){const snap=await runTransaction(db,async tx=>tx.get(meta));revision=snap.exists()?snap.data().revision:0;const [records,reports]=await Promise.all([getDocs(collection(db,'proRecords')),getDocs(collection(db,'proReports'))]);const settings=snap.data()||{};let result={version:1,records:Object.fromEntries(records.docs.map(d=>[d.id,d.data().record])),reports:reports.docs.map(d=>d.data().report),imports:settings.imports||[],rules:settings.rules||{},settings:settings.settings||{cut:10000,hub:''}};const check=await runTransaction(db,async tx=>tx.get(meta));if((check.data()?.revision||0)!==revision)throw Error('A base mudou durante a leitura. Entre novamente.');baseline=structuredClone(result);return result;},async save(state){const changed=Object.entries(state.records).filter(([id,r])=>JSON.stringify(r)!==JSON.stringify(baseline.records?.[id]));const reports=state.reports.filter(r=>!baseline.reports?.some(b=>b.id===r.id));for(const r of reports)if(new TextEncoder().encode(JSON.stringify(r)).length>850000)throw Error('Relatório muito grande para salvar na nuvem. Reduza a seleção.');const removed=Object.keys(baseline.records||{}).filter(id=>!state.records[id]);if(changed.length+reports.length+removed.length>400)throw Error('Lote muito grande para gravação compartilhada. Importe menos de 400 propostas por vez.');await runTransaction(db,async tx=>{const snapshot=await tx.get(meta);if((snapshot.data()?.revision||0)!==revision)throw Error('Outro usuário atualizou a base. Recarregue e entre novamente antes de salvar.');for(const [id,record] of changed)tx.set(doc(db,'proRecords',id),{record});for(const id of removed)tx.delete(doc(db,'proRecords',id));for(const report of reports)tx.set(doc(db,'proReports',report.id),{report});tx.set(meta,{revision:revision+1,settings:state.settings,rules:state.rules,imports:state.imports,updatedBy:credential.user.uid});});revision++;baseline=structuredClone(state);},async findEcs(codes){const found=[];for(const c of codes){const s=await getDocs(query(collection(db,'ecsRecords'),where('ecsCode','==',c)));found.push(...s.docs.map(d=>({id:d.id,...d.data()})));}return found;}};
}
