export const CODES={'70359':['equipment','Bomba sanitária'],'81600':['equipment','Válvula sanitária'],'81605':['part','Reparo de válvula sanitária'],'81601':['part','Unidade de controle / válvula solenoide'],'81611':['part','Reparo de bomba sanitária'],'81610':['part','Reparo de bomba industrial JP'],'81602':['part','Reparo de homogeneizador'],'81604':['part','Reparo de trocador de calor'],'81603':['part','Reparo de Liquiverter'],'81606':['equipment','Trocador de calor'],'81607':['equipment','Bomba industrial JP'],'81608':['equipment','Manifold de válvulas'],'81609':['part','Reparo de atomizador']};
export const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
export const money=s=>Math.round(Number(String(s).replace(/\./g,'').replace(',','.'))*100);
export const key=i=>`${i.code}|${norm(i.description).trim()}`;
export function classify(i,rules={}){if(rules[key(i)])return {...rules[key(i)],reason:'Classificação salva'};if(CODES[i.code])return {type:CODES[i.code][0],spx:'yes',reason:`Código coringa · ${CODES[i.code][1]}`};const d=norm(i.description);let type=/^(KIT|SELO|RETENTOR|ROTOR|ANEL|JUNTA|EIXO|ROLAMENTO|GAXETA|LUVA|MOLA|PARAFUSO|ARRUELA|CHAVE|ANILHA|VED\.|CAIXA|UNIDADE CONTR|ATUADOR|ADAPTADOR|VALVULA SOL|VALV\. SOL)/.test(d)?'part':/^(BOMBA |BOMBEADOR |VALVULA |VALV\. |TROCADOR DE CALOR|HOMOGENEIZADOR|MANIFOLD)/.test(d)?'equipment':'unknown';let spx=/SPX|WAUKESHA|\bAPV\b|\bW\+|\bWS\+|\bWI\+|\bU[123][- /]|\bH\d{6}\b|\bL\d{6}\b|LIQUIV|RANNIE|GAULIN|\bDA3|\bSVS?1?\b|\bSW ?4[234]?\b|\bVPN\b|\bTLP\b|\bMDL\b|\bBOMBA SP4\b/.test(d)?'probable':'unknown';return {type,spx,reason:'Sugestão pela descrição; confirmar SPX'};}
export const stamp=(d,t='00:00')=>{const [day,month,year]=d.split('/');return `${year}-${month}-${day}T${t}:00`;};
function clean(text){return text.split('\n').filter(l=>!/^\s*(Sistema Corporativo|Fiedler Aut\.|C\.0164\.|Acompanhamento Prospostas|Status:|Pág\.)/.test(l)).join('\n');}
export function parseText(text,source){let out=[];for(let b of clean(text).split(/(?=Proposta:\s*PRO-\d+)/).filter(b=>/^Proposta:/.test(b))){const h=b.match(/Proposta:\s*(PRO-\d+)\s+Status:\s*(.*?)\s+(\d{2}\/\d{2}\/\d{4})\s+(\d{2}:\d{2})/);if(!h)throw Error('Cabeçalho de proposta não reconhecido.');let get=re=>b.match(re)?.[1]?.trim()||'';let total=get(/Total proposta:\s*([\d.,]+)/);if(!total)throw Error(`${h[1]} sem total: importação interrompida para conferência.`);let notes=get(/Obs:\s*([\s\S]*?)\n\s*Item\s+Código/);let items=[];for(let line of b.split('\n')){let m=line.match(/^\s*(\d+)\s+(\d+)\s+(.+?)\s+([\d.,]+)\s+([\d.,]+)\s+([\d.,]+)\s*$/);if(m)items.push({line:m[1],code:m[2],description:m[3].trim(),qty:Number(m[4].replace(/\./g,'').replace(',','.')),unit:money(m[5]),total:money(m[6])});}
let p={id:h[1],status:h[2].trim(),statusAt:stamp(h[3],h[4]),client:get(/Cliente:\s*(.*?)Município:/),city:get(/Município:\s*(.*?)Televendas:/),seller:get(/Vendedor:\s*([^\n]+)/),inside:get(/Televendas:\s*([^\n]+)/),contact:get(/Contato:\s*(.*?)Telefone:/),email:get(/e-mail:[ \t]*([^\n]*)/),reason:get(/Motivo status:[ \t]*([^\n]*)/),notes,items,total:money(total),currency:/DOLAR|DÓLAR|USD|US\$/.test(norm(notes))?'USD':/EURO|EUR|€/.test(norm(notes))?'EUR':'BRL',currencyBasis:'BRL presumido quando não indicado no relatório',ecs:[...new Set(b.match(/ECS-[A-Z]{2,4}-\d{2}-\d{4,6}/g)||[])],charges:get(/Cobranças:\s*([\s\S]*?)(?:Total Status:|$)/),source,importedAt:new Date().toISOString(),origin:'pdf'};
p.errors=[];if(!items.length)p.errors.push('Nenhum item lido');if(items.reduce((a,i)=>a+i.total,0)!==p.total)p.errors.push('Soma dos itens diverge do total');if(items.some(i=>Math.abs(Math.round(i.qty*i.unit)-i.total)>2))p.errors.push('Quantidade × unitário diverge do total do item');p.possibleOVC=items.some(i=>i.unit>0&&i.unit<=10)||/\bOVC\b|ORDEM.*COMPLEMENTAR/.test(norm(notes));out.push(p);}if(!out.length)throw Error('Nenhuma PRO encontrada. Use PDF Benner com texto selecionável.');return out;}
export function fingerprint(p){const {source,importedAt,...rest}=p;return JSON.stringify(rest);}
export function merge(old,p){if(!old)return {data:p,history:[p],manual:{owner:'',last:'',next:'',comments:'',exclude:false,excludeReason:'',classifications:{},ecs:[],reviewed:false},rev:0};let v=structuredClone(old);if(!v.history.some(x=>fingerprint(x)===fingerprint(p)))v.history.push(p);if(p.statusAt>v.data.statusAt||(p.statusAt===v.data.statusAt&&p.origin==='pdf'))v.data=p;return v;}
export function evaluate(record,scope='part',rules={}){let p=record.data,m=record.manual;let items=p.items.map(i=>({...i,c:m.classifications?.[i.line]||classify(i,rules)}));let uncertain=items.some(i=>i.c.spx==='unknown'||i.c.spx==='probable'||(i.c.spx==='yes'&&i.c.type==='unknown'));let subtotal=items.filter(i=>i.c.spx==='yes'&&(scope==='all'||i.c.type===scope)).reduce((a,i)=>a+i.total,0);let fallback=uncertain||!items.length;return {items,value:fallback?p.total:subtotal,fallback,excluded:m.exclude||p.currency!=='BRL',pending:uncertain||!!p.errors?.length||(p.possibleOVC&&!m.ovcChecked),type:[...new Set(items.map(i=>i.c.type))].join(',')};}
